enableScripts: false

nodeLinker: node-modules

packageExtensions:
  'eslint-plugin-perfectionist@*':
    dependencies:
      typescript: '^5.8.3'
  'vite-plugin-dts@*':
    dependencies:
      typescript: '^5.8.3'
